#!/usr/bin/env bash
echo Creating users database...
docker-compose exec users python manage.py recreate-db
echo Creating keyvault database...
docker-compose exec keyvault python manage.py recreate-db
